import React from 'react'
import { assets } from '../assets/frontend_assets/assets'

function About() {
  return (
    <div>
      <div><div className="pt-8 text-2xl text-center border-t"><div className="inline-flex items-center gap-2 mb-3"><p className="text-gray-500">ABOUT <span className="font-medium text-gray-700">US</span></p><p className="w-8 sm:w-12 h-[1px] sm:h-[2px] bg-gray-700"></p></div></div><div className="flex flex-col gap-16 my-10 md:flex-row"><img className="w-full md:max-w-[450px]" src={assets.about_img} alt=""/><div className="flex flex-col justify-center gap-6 text-gray-600 md:w-2/4"><p>Bigby's was born out of a passion for innovation and a desire to revolutionize the way people shop online. Our journey began with a simple idea: to provide a platform where customers can easily discover, explore, and purchase a wide range of products from the comfort of their homes.</p><p>Since our inception, we've worked tirelessly to curate a diverse selection of high-quality products that cater to every taste and preference. From fashion and beauty to electronics and home essentials, we offer an extensive collection sourced from trusted brands and suppliers.</p><b className="text-gray-800">Our Mission</b><p>Our mission at Bigby's is to empower customers with choice, convenience, and confidence. We're dedicated to providing a seamless shopping experience that exceeds expectations, from browsing and ordering to delivery and beyond.</p></div></div><div className="py-4 text-xl "><div className="inline-flex items-center gap-2 mb-3"><p className="text-gray-500">WHY <span className="font-medium text-gray-700">CHOOSE US</span></p><p className="w-8 sm:w-12 h-[1px] sm:h-[2px] bg-gray-700"></p></div></div><div className="flex flex-col mb-20 text-sm md:flex-row"><div className="flex flex-col gap-5 px-10 py-8 border md:px-16 sm:py-20"><b>Quality Assurance:</b><p className="text-gray-600 ">We meticulously select and vet each product to ensure it meets our stringent quality standards.</p></div><div className="flex flex-col gap-5 px-10 py-8 border md:px-16 sm:py-20"><b>Convenience:</b><p className="text-gray-600 ">With our user-friendly interface and hassle-free ordering process, shopping has never been easier.</p></div><div className="flex flex-col gap-5 px-10 py-8 border md:px-16 sm:py-20"><b>Exceptional Customer Service:</b><p className="text-gray-600 ">Our team of dedicated professionals is here to assist you the way, ensuring your satisfaction is our top priority.</p></div></div><div className="text-center "><p className="text-2xl font-medium text-gray-800">Subscribe now &amp; get 20% off</p><p className="mt-3 text-gray-400">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p><form onSubmit={(e)=>e.preventDefault()} className="flex items-center w-full gap-3 pl-3 mx-auto my-6 border sm:w-1/2"><input className="w-full outline-none sm:flex-1" type="email" placeholder="Enter your email" required=""/><button type="submit" className="px-10 py-4 text-xs text-white bg-black">SUBSCRIBE</button></form></div></div>
    </div>
  )
}

export default About
